dist: bionic
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script: 
 - sudo cat /etc/docker/daemon.json
 - sudo systemctl status docker
 - docker version
 - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
 - sudo systemctl restart docker
 - docker version 
